### ISSUE TITLE
Username/password authenticator password encoding issue

### ISSUE THREAD

**Issue by mullerch** [nats-io/nats.deno#237]
## Reproduce

1. Run a nats server with the following configuration:
```
listen: 0.0.0.0:4222

authorization {
    username: admin
    password: §12§12§12
}

websocket {
    listen: 0.0.0.0:443
    no_tls: true
}
```
2. Connect to the server with the ws client usgin username/password auth

### Expected result

The client can authenticate successfully

### Effective result

The client receives an "Authentication Violation" error.

## Debug

When running a custom server and registering a custom authenticator, we can print the received password and we notice that the encoding of `§` character is wrong.

## Workaround

Encode the password in base64 when passing it to the connect function. Create a custom authenticator on the server side and decode the password.

**Comment by aricart** [comment]
@mullerch thanks for the great report - this bug is a general encoding/decoding issue. Since payloads are encoded/decoded separately this is only an issue for non-payload data (such as the connect) and potentially headers or subjects. The new encoding strategy uses TextEncoder/Decoder, and even if less performant will always be correct.

**Comment by aricart** [comment]
@mullerch `npm update nats.ws@next` to get a build with the fix. I will release it once some changes to KV land.

**Comment by mullerch** [comment]
Thanks for the quick fix
