### ISSUE TITLE
uncaught exceptions on nats disconnect when using jetstream fetch()

### ISSUE THREAD

**Issue by reecefenwick** [nats-io/nats.deno#416]
Hi there,

We have discovered an issue specifically with `fetch()` and how it deals with the NATS server being taken offline

Client Version - `2.9.0` 
Server Version - `2.9.8`

(I have also tested several other versions)

### Steps to reproduce
1. Run nats with jetstream `docker run -d --name=nats-reproduce -p 4222:4222 nats --js`
2. Run minimal reproduction below `ts-node reproduce.ts`
  * This will create a test stream, consumer and recursively call fetch
3. Optionally publish to the test stream `nats pub test 'hello'
4. Stop the nats server `docker stop nats-reproduce
**5. After a few seconds the process will exit**

`reproduce.ts`

```typescript
import {
  AckPolicy,
  connect,
  ConsumerConfig,
  DeliverPolicy,
  JetStreamManager,
  nanos,
  ReplayPolicy,
} from 'nats';
import { setTimeout } from 'timers/promises';

const streamName = 'test';

async function setupTestStream(jsm: JetStreamManager) {
  try {
    await jsm.streams.add({
      name: 'test',
      subjects: ['test'],
    });
  } catch (ignore) {
    console.error(ignore);
  }
}

async function configureConsumer(jsm: JetStreamManager) {
  const config: Partial<ConsumerConfig> = {
    deliver_policy: DeliverPolicy.New,
    ack_policy: AckPolicy.Explicit,
    ack_wait: nanos(1000),
    max_deliver: 100,
    replay_policy: ReplayPolicy.Instant,
    durable_name: 'my-durable',
    filter_subject: '>',
  };

  await jsm.consumers.add(streamName, config);
}

async function main() {
  const nc = await connect({
    servers: ['localhost:4222'],
    reconnect: true,
    maxReconnectAttempts: -1,
  });

  console.log('connected');

  const js = nc.jetstream();
  const jsm = await nc.jetstreamManager();

  await setupTestStream(jsm);
  await configureConsumer(jsm);

  while (true) {
    try {
      console.log('fetching');

      const msgs = js.fetch('test', 'my-durable', {
        batch: 1,
        no_wait: true,
        expires: 3000,
      });

      for await (const m of msgs) {
        console.log(m.sid);
        m.ack();
      }
    } catch (e) {
      // expecting nats connection disconnected errors to be thrown here
      console.error(e);
    }
    await setTimeout(1000);
  }
}

main()

```

### What I expect to happen

I expect the error to be thrown by fetch() or the iterator returned by it.

Let me know if I can provide any more information

**Comment by ReeceSwyftx** [comment]
Thanks @aricart I can confirm this resolves the issue I was seeing.

An observation though, when the NATS server has been shutdown, my reproduction above does not encounter any errors at all, not even in the try/catch I have. Is that expected? 

Should `fetch()` reject if the underlying connection to the server is in a bad state?

**Comment by aricart** [comment]
@ReeceSwyftx so a few things - while it is possible to get errors from the iterator, the API for fetch doesn't return a promise, so the only rejection that can happen is an error in the iterator. This is a flaw in the `fetch()` API which will be addressed in the JetStream simplification (before the end of this year). 

One thing that will help in understanding is that fetch operates much like a subscription unless the error is something that is unexpected (like a permission error, etc), it should be transparent.  Let me clarify, if you have a regular subscription and you disconnect and you have reconnects enabled, the subscription will stop processing messages, but once it reconnects it resumes. 

Now for fetch it sort of works as a subscription. We publish a message, but it isn't a request that succeeds if delivered (we have no idea if the request publish went through) - the server actually doesn't even respond if the stream and or consumer doesn't exist. IE there's no response or error that tells us if we did a fetch on a stream or consumer that doesn't exist. All we know is no messages were streamed back.

On a disconnect, things operate in a similar way - if the disconnect happened before it went to the server, we have no idea, and we won't receive a confirmation (the expiration is what terminates the request).

What this means is that without heartbeats enabled, you cannot tell if the lack of messages is due to the client being disconnected or no messages. Thus the reasoning that not getting messages because you are disconnected shouldn't really be an error unless you want to monitor for heartbeats.

Now the unfortunate part is that fetch - idle heartbeats on an iterator were broken, but I have just fixed it. https://github.com/nats-io/nats.deno/issues/419
